[package]
name = "near-doc"
version = "0.1.1"
authors = ["Luis Mastrangelo <luismastrangelo@gmail.com>"]
edition = "2018"
repository = "https://github.com/acuarica/near-doc"
homepage = "https://github.com/acuarica/near-doc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "1.0.14", features = ["full", "fold", "visit", "extra-traits", "printing"] }
quote = "1.0"
proc-macro2 = "1.0"
clap = "2.32"
chrono = "0.4"
